# This is a basic workflow to help you get started with Actions
name: Hello World

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Pull
        run: docker pull rss-reader-core:sha256-274a8ef9beb0182b4d3e82f4442b6867e276000c6a57aece74ccee64a8a7d3d9.sig
      - name: Docker run
        run: docker run rss-reader-core:sha256-274a8ef9beb0182b4d3e82f4442b6867e276000c6a57aece74ccee64a8a7d3d9.sig